// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-It4c14VEv634DrCI9J8hYERXVOC_CE8',
    appId: '1:323147047576:android:ae0efe91be458b1c15a6ed',
    messagingSenderId: '323147047576',
    projectId: 'locket-186a4',
    // storageBucket: 'locket-186a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-It4c14VEv634DrCI9J8hYERXVOC_CE8',
    appId: '1:323147047576:ios:8be759bb45bf25e415a6ed',
    messagingSenderId: '323147047576',
    projectId: 'locket-186a4',
    // storageBucket: 'locket-186a4.firebasestorage.app',
    iosBundleId: 'com.example.locket',
  );
}
